# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [push]

jobs:
  build:
    name: Build jar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo in ubuntu file system
        uses: actions/checkout@v1
      - name: Print contents
        run: ls -la
